spring:
  datasource:
    url: jdbc:postgres://course_db_iolt_user:R8rC5W3FNFiNhRwv9DV0X8nQb0LPTTJY@dpg-cll0l7sjtl8s73f4s2a0-a/course_db_iolt
    driver-class-name: org.postgresql.Driver
    username: course_db_iolt_user
    password: R8rC5W3FNFiNhRwv9DV0X8nQb0LPTTJY
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 9la9g493ghlgmarthr0429urul4301yh937gc763fe87p8a8oag3gf
  lifetime: 59m